AWSTemplateFormatVersion: 2010-09-09
Description: DynamoDB_Template

Resources:
  UserDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: User_Order
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: product_id
          AttributeType: S
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: product_id
          KeyType: RANGE
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableClass: STANDARD_INFREQUENT_ACCESS
      GlobalSecondaryIndexes:
        - IndexName: product_id-user_id-index
          KeySchema:
            - AttributeName: product_id
              KeyType: HASH
            - AttributeName: user_id
              KeyType: RANGE
          Projection: 
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5
